name: Run Unit & Integration Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-deps-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        uses: smithki/xvfb-action@v1.0.4
        with:
          run: npm run test:unit

      - name: Run integration tests
        uses: smithki/xvfb-action@v1.0.4
        with:
          run: npm run test:integration
